spring:
  application:
    name: eai-user-management-service  
  config:
    import: optional:configserver:${eai-config-server-details:http://localhost:8888}
  jmx:
    enabled: true
    #To allow circular dependency or use @Lazy on the bean
  # main:
  #   allow-circular-references: true  
  #property set into pom.xml
  # profiles:
  #   active: @spring.profiles.active@  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 888019418247-ljumvo6njfjh8q2lqhm1d875d55lujpd.apps.googleusercontent.com
            client-secret: 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

  devtools:
    livereload:
      enabled: true  

server:
  port: 9008
  servlet:
    contextPath: /eai/api/user-management
#for actuator update		
management:
  endpoints:
    web:
      exposure:
        include: health, refresh, conditions
    jmx:
      exposure:
        include: health, refresh, info    

application:
  title: App Customer
  version: 1.2        