spring:
  application:
    name: eai-user-management-service  
  config:
    import: optional:configserver:${eai_config_server_details:http://localhost:8888}
  jmx:
    enabled: true
    #To allow circular dependency or use @Lazy on the bean
  # main:
  #   allow-circular-references: true  
  #property set profile @spring.profiles.active@ into pom.xml
  profiles:
    active: ${ACTIVE_PROFILE}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 888019418247-ljumvo6njfjh8q2lqhm1d875d55lujpd.apps.googleusercontent.com
            client-secret: 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

  devtools:
    livereload:
      enabled: true  

server:
  port: ${CONTAINER_PORT:9008}
  servlet:
    contextPath: /eai/api/user-management
#for actuator update		
management:
  endpoints:
    web:
      exposure:
        include: health, refresh, conditions
    jmx:
      exposure:
        include: health, refresh, info    
ui:
  app:
    url: ${UI_APP_URL}
application:
  title: App Customer
  version: 2.0        