spring:
  application:
    name: eai-user-management-service
  config:
    import: ${eai-config-server-details:configserver:http://localhost:8888}
  
server:
  port: 9008
  servlet:
    contextPath: /eai/api/user-management